### ISSUE TITLE
Add another measurement cycle in the beginning for taking background with no radiation source

### ISSUE THREAD

**Issue by johnnykfeng** [johnnykfeng/H3D-Mapper#3]
As Saketh described, having a measurement of background is pretty important. That should be in cycle 0, and the last cycle could be for taking counts with the mask removed

**Comment by shreyasivakumar** [comment]
Added measurement -1 where there is no source and no mask in the way (background study) and measurement 0 where the source is placed but the mask is still out of the way.
Link to commits:
a747daa
d513804
